### ISSUE TITLE
Base de datos de Productos

### ISSUE THREAD

**Issue by dantealegria1** [dantealegria1/ProjectAbarrotes#1]

**Comment by dantealegria1** [comment]
[Portafolio_oml.pdf](https://github.com/user-attachments/files/17337194/Portafolio_oml.pdf)

**Comment by dantealegria1** [comment]
Ya funciona todo, si alguien lo puede calar estaría e perlas
![PHOTO-2024-10-12-00-41-34](https://github.com/user-attachments/assets/8de77fa2-be79-4769-bfa4-924837a25df8)

**Comment by dantealegria1** [comment]
SHOW DATABASES;
USE abarrotes_db;
CREATE TABLE Producto (
                          idProducto INT AUTO_INCREMENT PRIMARY KEY,
                          nombreProducto VARCHAR(255) NOT NULL,
                          descripcion TEXT,
                          presentacion VARCHAR(100),
                          caducidad DATE,
                          precioProv FLOAT,
                          precioUni FLOAT,
                          existencias INT,
                          fech DATE,
                          marca VARCHAR(100),
                          idProveedor INT,
                          idPaquete INT, -- Clave foránea para la tabla Paquete
                          idInventario INT -- Clave foránea para la tabla Inventario
);
-- Producto prueba
INSERT INTO Producto (nombreProducto, descripcion, presentacion, caducidad, precioProv, precioUni, existencias, fech, marca, idProveedor, idPaquete, idInventario, id)
VALUES (
           'Galletas de Chocolate',
           'Galletas con chispas de chocolate',
           'Paquete de 200g',
           '2025-12-31',
           10.50,
           15.00,
           100,
           '2024-10-11',
           'MarcaGenérica',
           1,
           1,
           1,
           0
       );
ALTER TABLE Producto DROP COLUMN id;

SELECT * FROM abarrotes_db.Producto;

describe Producto

**Comment by DiegoAlb09** [comment]
![Captura de pantalla 2024-10-12 195635](https://github.com/user-attachments/assets/e241b79b-0452-42ff-9243-0feff7553a2e)
